image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Build PATS
        services:
          - docker
        script:
          - docker run --rm --volume $(pwd):/app prooph/composer:7.3 install
          - docker run --rm --volume $(pwd):/app prooph/composer:7.3 update
          - make setup-mysql
          - make setup-apache
          - make setup-network
    - step:
        name: Run Tests
        script:
          - make codeception-vvv