image: php:7.3

pipelines:
  default:
    - step:
        name: Build & Run PATS
        services:
          - docker
        script:
          - apt-get update && apt-get install -y unzip mysql-client libpng-dev libpq-dev
          - docker-php-ext-install mysqli pdo pdo_mysql zip mbstring opcache gd sockets
          - docker-php-ext-enable zip
          - docker run --rm --volume $(pwd):/app prooph/composer:7.3 install
          - docker run --rm --volume $(pwd):/app prooph/composer:7.3 update
          - make setup-mysql
          - make setup-apache
          - make setup-network
          - make codeception-vvv